// 솔로(프리뷰 전용)/부모(순환 가드)/매트 팝오버(알파·해제)
import { launchApp, checker, sessionSource } from './_helpers.mjs'

const { browser, page } = await launchApp()
const { ok, done } = checker('SPM')
const src = () => sessionSource(page)
const btnsOf = async (i) => {
  const rows = await page.$$('.timeline__label--row')
  await rows[i].hover(); await page.waitForTimeout(120)
  return rows[i].$$('.timeline__lbtn')
}
// 렌더된 SVG 레이어 수 (솔로 검증 — 프리뷰에만 적용)
const visibleSvgLayers = async () => page.evaluate(() => {
  const svg = document.querySelector('.preview__lottiewrap svg')
  return svg ? [...svg.querySelectorAll(':scope > g > g')].filter((g) => g.style.display !== 'none').length : -1
})
// 1) 솔로 — 프리뷰 레이어 수 감소, sourceData hd는 안 건드림
const n0 = await visibleSvgLayers()
await (await btnsOf(0))[2].click()
await page.waitForTimeout(1300)
let d = await src()
ok(d.layers[0].xsolo === true, '솔로 플래그')
ok(d.layers.every((l) => l.hd !== true), 'sourceData hd 오염 없음')
const n1 = await visibleSvgLayers()
ok(n1 < n0 && n1 >= 1, `프리뷰 솔로 렌더 (${n0} → ${n1})`)
// 해제 → 복원
await (await btnsOf(0))[2].click()
await page.waitForTimeout(1300)
d = await src()
ok(d.layers.every((l) => l.xsolo !== true && l.hd !== true), '솔로 해제 → 전부 복원')
ok((await visibleSvgLayers()) === n0, `프리뷰 복원 (${await visibleSvgLayers()})`)
// 2) 매트 — 팝오버 (소스 선택 → 알파 자동)
await (await btnsOf(1))[0].click()
await page.waitForTimeout(300)
await (await page.$$('.mattepop .parentpop__item'))[0].click() // 첫 후보 = layer0
await page.waitForTimeout(1300)
d = await src()
ok(d.layers[1].tt === 1 && d.layers[0].td === 1, `매트 알파 (tt=${d.layers[1].tt}, tp=${d.layers[1].tp})`)
await page.locator('.mattepop__tab', { hasText: '없음' }).click()
await page.waitForTimeout(1300)
await page.mouse.click(1400, 60)
await page.waitForTimeout(200)
d = await src()
ok(d.layers[1].tt === undefined && d.layers[0].td === undefined, '없음 → 해제')
// 3) 부모
await (await btnsOf(1))[1].click()
await page.waitForTimeout(300)
await (await page.$$('.parentpop__item'))[1].click()
await page.waitForTimeout(1300)
d = await src()
ok(d.layers[1].parent === d.layers[0].ind, `부모 설정 (${d.layers[1].parent})`)
await (await btnsOf(0))[1].click()
await page.waitForTimeout(300)
await (await page.$$('.parentpop__item'))[1].click()
await page.waitForTimeout(1300)
d = await src()
ok(d.layers[0].parent === undefined, '순환 가드')
await (await btnsOf(1))[1].click()
await page.waitForTimeout(300)
await (await page.$$('.parentpop__item'))[0].click()
await page.waitForTimeout(1300)
d = await src()
ok(d.layers[1].parent === undefined, '부모 해제')
ok(await page.evaluate(() => !!document.querySelector('.preview__lottiewrap svg')), '렌더 정상')
await done(browser)

